require_relative "kuromusic/version"
require_relative "kuromusic/MIDI"
require_relative "kuromusic/Scale"
require_relative "kuromusic/Track"
require_relative "kuromusic/Chord_"
require_relative "kuromusic/MelodyGenerator"
require_relative "kuromusic/RhythmMachine"
require_relative "kuromusic/ChordProgGenerator"
